# Generated by Django 4.2.6 on 2023-11-02 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_ircevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="ircevent",
            name="inserted_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
