# Generated by Django 4.2.6 on 2023-12-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_ircevent_inserted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ircevent",
            name="event_source",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
