# Generated by Django 4.2.6 on 2023-12-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_ircevent_event_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ircevent",
            name="event_target",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
