# Generated by Django 4.2.6 on 2023-11-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ircclient",
            name="name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="ircclient",
            name="sasl_login",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name="ircclient",
            name="sasl_passwd",
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
